### PR TITLE
Fix avatar attachment positions.

### LINKED ISSUE #142: The avatar's bounding box needs to be recalculated when in a sit/pose animation.
This would allow the player's nametag's height, collider extents, and camera target position to adjust to match the new dimensions of the pose. Currently:
image

Relates to #137.

### LINKED ISSUE #180: point camera at head bone after activating sit animations
Right now if you use a sit animation, the camera stays fixed where the head used to be.  This is a bit off-putting.  We should make it so the camera stays with the head bone during these animations (unless we unlock it). Then it can reset back to the original position when an avatar get's back up.

### PR DESCRIPTION
**Pull request by Gigabyte5671**
This PR fixes the attachment of the camera and nametag to the player's avatar.
Previous:
nametags float far above the avatar's head when sitting

Updated:
nametags are correctly positioned above the avatar's head when sitting

[Video example of the new camera attachment.](https://drive.google.com/file/d/1G1Dm_rrTqxqq322qAdmbjyvpAJGTS5ju/view?usp=sharing)

---

A "Camera Bobbing" toggle has been added to the graphics settings menu. This toggles the bouncing/bobbing effect visible in first-person view that results from the new camera attachment method. (This setting is enabled by default).
image

---

This PR also adds a rolling average [hysteresis utility class](https://github.com/vircadia/vircadia-web/blob/473deda2fb9be952c4fdcee529d82eb482e51f7f/src/modules/utility/hysteresis.ts). This utility acts as a low-pass filter, smoothing values that change frequently.

---

Closes #180.
Closes #142.

### CODE REVIEW

**Comment by digisomni** [comment]
We should put the setting in the control settings as it's more a UX thing than a graphical thing.

**Comment by Gigabyte5671** [comment]
Sounds good. Where abouts in the control settings menu do you think it should go?

**Comment by digisomni** [comment]
Let's add a tab for "Camera" with an eye icon.

**Comment by Gigabyte5671** [comment]
> Let's add a tab for "Camera" with an eye icon.

Added with commit [20dd0c7](https://github.com/vircadia/vircadia-web/pull/181/commits/20dd0c79720bed9fbf94669b968962770edda620).

**Pull request merged**
